### ISSUE TITLE
What arguments should the julia process run with.

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/BenchmarksGame.jl#17]
Clearly, `--check-bounds=no`. How about `--math-mode=fast`? If tests pass, arguably we should run with fast math mode. What do other languages do?

**Comment by chethega** [comment]
Against `--math-mode=fast`. This is terribly unsound, considering things like the `sinpi` issue. 

`@fastmath` is fair and idiomatic. I don't think a lot of real-world projects should use `--math-mode=fast`. Other languages use fastmath, but this is fair in C: You set the flags per source-file, not per process.

Also against `--check-bounds=no`. We want to showcase how boundscheck elision works. If `Base` has an issue where some critical boundscheck cannot be elided from user code, then we need an additional `@propagate_inbounds` in `Base`, and should fairly report the slower speed until the PR has landed, either via backport point release or via release of 1.1.

**Comment by KristofferC** [comment]
Ok, default arguments make sense.

Only need to make sure `JULIA_NUM_THREADS` is set.

**Comment by KristofferC** [comment]
Yeah, after SLP being in O2 Im not sure what O3 does really.
